In [83]:
import numpy as np
import matplotlib.pyplot as plt # plotting data
import pandas as pd # since we have mixed data types, pandas will be a better option
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_squared_error
import seaborn as sns
from sklearn.model_selection import cross_val_score
from sklearn.metrics import r2_score


from sklearn.linear_model import Ridge, Lasso, LassoCV, ElasticNet, SGDRegressor

In [84]:
##############################################
# Data Preprocessing and Feature Engineering #
##############################################

In [85]:
# load the dataset
train_data = pd.read_csv("dataset/train.csv")
test_data = pd.read_csv("dataset/test.csv")

In [86]:
# Splitting data into features X and target y
X = train_data.drop(columns = ['SalePrice', 'Id', 'GarageArea', 'TotRmsAbvGrd']) # We drop SalePrice because it's our target, and drop Id because it has no meaning while training the model
y = train_data['SalePrice']
X_test = test_data.drop(columns = ['Id', 'GarageArea', 'TotRmsAbvGrd'])

In [87]:
# Splitting features into two categories, Categorical and numerical, to apply one-hot encoding to the categorical data
X_categorical = X.select_dtypes(include = ['object']).columns.tolist()
X_numerical = X.select_dtypes(exclude = ['object']).columns.tolist()

In [88]:
# Finding correlated data
X[X_numerical].corr()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageCars,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold
MSSubClass,1.000000,-0.386347,-0.139781,0.032628,-0.059316,0.027850,0.040581,0.022936,-0.069836,-0.065649,...,-0.040110,-0.012579,-0.006100,-0.012037,-0.043825,-0.026030,0.008283,-0.007683,-0.013585,-0.021407
LotFrontage,-0.386347,1.000000,0.426095,0.251646,-0.059213,0.123349,0.088866,0.193458,0.233633,0.049900,...,0.285691,0.088521,0.151972,0.010700,0.070029,0.041383,0.206167,0.003368,0.011200,0.007450
LotArea,-0.139781,0.426095,1.000000,0.105806,-0.005636,0.014228,0.013788,0.104160,0.214103,0.111170,...,0.154871,0.171698,0.084774,-0.018340,0.020423,0.043160,0.077672,0.038068,0.001205,-0.014261
OverallQual,0.032628,0.251646,0.105806,1.000000,-0.091932,0.572323,0.550684,0.411876,0.239666,-0.059119,...,0.600671,0.238923,0.308819,-0.113937,0.030371,0.064886,0.065166,-0.031406,0.070815,-0.027347
OverallCond,-0.059316,-0.059213,-0.005636,-0.091932,1.000000,-0.375983,0.073741,-0.128101,-0.046231,0.040229,...,-0.185758,-0.003334,-0.032589,0.070356,0.025504,0.054811,-0.001985,0.068777,-0.003511,0.043950
YearBuilt,0.027850,0.123349,0.014228,0.572323,-0.375983,1.000000,0.592855,0.315707,0.249503,-0.049107,...,0.537850,0.224880,0.188686,-0.387268,0.031355,-0.050364,0.004950,-0.034383,0.012398,-0.013618
YearRemodAdd,0.040581,0.088866,0.013788,0.550684,0.073741,0.592855,1.000000,0.179618,0.128451,-0.067759,...,0.420622,0.205726,0.226298,-0.193919,0.045286,-0.038740,0.005829,-0.010286,0.021490,0.035743
MasVnrArea,0.022936,0.193458,0.104160,0.411876,-0.128101,0.315707,0.179618,1.000000,0.264736,-0.072319,...,0.364204,0.159718,0.125703,-0.110204,0.018796,0.061466,0.011723,-0.029815,-0.005965,-0.008201
BsmtFinSF1,-0.069836,0.233633,0.214103,0.239666,-0.046231,0.249503,0.128451,0.264736,1.000000,-0.050117,...,0.224054,0.204306,0.111761,-0.102303,0.026451,0.062021,0.140491,0.003571,-0.015727,0.014359
BsmtFinSF2,-0.065649,0.049900,0.111170,-0.059119,0.040229,-0.049107,-0.067759,-0.072319,-0.050117,1.000000,...,-0.038264,0.067898,0.003093,0.036543,-0.029993,0.088871,0.041709,0.004940,-0.015211,0.031706
BsmtUnfSF,-0.140759,0.132644,-0.002618,0.308159,-0.136841,0.149040,0.181133,0.114442,-0.495251,-0.209294,...,0.214175,-0.005316,0.129005,-0.002538,0.020764,-0.012579,-0.035092,-0.023837,0.034888,-0.041258
TotalBsmtSF,-0.238518,0.392075,0.260833,0.537808,-0.171098,0.391452,0.291066,0.363936,0.522396,0.104810,...,0.434585,0.232019,0.247264,-0.095478,0.037384,0.084489,0.126053,-0.018479,0.013196,-0.014969
1stFlrSF,-0.251758,0.457181,0.299475,0.476224,-0.144203,0.281986,0.240379,0.344501,0.445863,0.097117,...,0.439317,0.235459,0.211671,-0.065292,0.056104,0.088758,0.131525,-0.021096,0.031372,-0.013604
2ndFlrSF,0.307886,0.080177,0.050986,0.295493,0.028942,0.010308,0.140024,0.174561,-0.137079,-0.099260,...,0.183926,0.092165,0.208026,0.061989,-0.024358,0.040606,0.081487,0.016197,0.035164,-0.028700
LowQualFinSF,0.046474,0.038469,0.004779,-0.030429,0.025494,-0.183784,-0.062419,-0.069071,-0.064503,0.014807,...,-0.094480,-0.025444,0.018251,0.061081,-0.004296,0.026799,0.062157,-0.003793,-0.022174,-0.028921
GrLivArea,0.074853,0.402797,0.263116,0.593007,-0.079686,0.199010,0.287389,0.390857,0.208171,-0.009640,...,0.467247,0.247433,0.330224,0.009113,0.020643,0.101510,0.170205,-0.002416,0.050240,-0.036526
BsmtFullBath,0.003491,0.100949,0.158155,0.111098,-0.054942,0.187599,0.119470,0.085310,0.649212,0.158678,...,0.131881,0.175315,0.067341,-0.049911,-0.000106,0.023148,0.067616,-0.023047,-0.025361,0.067049
BsmtHalfBath,-0.002333,-0.007234,0.048046,-0.040150,0.117821,-0.038162,-0.012337,0.026673,0.067418,0.070948,...,-0.020891,0.040161,-0.025324,-0.008555,0.035114,0.032121,0.020025,-0.007367,0.032873,-0.046524
FullBath,0.131608,0.198769,0.126031,0.550600,-0.194149,0.468271,0.439046,0.276833,0.058543,-0.076444,...,0.469672,0.187703,0.259977,-0.115093,0.035353,-0.008106,0.049604,-0.014290,0.055872,-0.019669
HalfBath,0.177354,0.053532,0.014259,0.273458,-0.060769,0.242656,0.183331,0.201444,0.004262,-0.032148,...,0.219178,0.108080,0.199740,-0.095317,-0.004972,0.072426,0.022381,0.001290,-0.009050,-0.010269
BedroomAbvGr,-0.023438,0.263170,0.119690,0.101676,0.012980,-0.070651,-0.040581,0.102821,-0.107355,-0.015728,...,0.086106,0.046854,0.093810,0.041570,-0.024478,0.044300,0.070703,0.007767,0.046544,-0.036014
KitchenAbvGr,0.281721,-0.006069,-0.017784,-0.183882,-0.087001,-0.174800,-0.149598,-0.037610,-0.081007,-0.040751,...,-0.050634,-0.090130,-0.070091,0.037312,-0.024600,-0.051613,-0.014525,0.062341,0.026589,0.031687
Fireplaces,-0.045569,0.266639,0.271364,0.396765,-0.023820,0.147716,0.112581,0.249070,0.260011,0.046921,...,0.300789,0.200019,0.169405,-0.024822,0.011257,0.184530,0.095074,0.001409,0.046357,-0.024096
GarageYrBlt,0.085072,0.070250,-0.024947,0.547766,-0.324297,0.825667,0.642277,0.252691,0.153484,-0.088011,...,0.588920,0.224577,0.228425,-0.297003,0.023544,-0.075418,-0.014501,-0.032417,0.005337,-0.001014
GarageCars,-0.040110,0.285691,0.154871,0.600671,-0.185758,0.537850,0.420622,0.364204,0.224054,-0.038264,...,1.000000,0.226342,0.213569,-0.151434,0.035765,0.050494,0.020934,-0.043080,0.040522,-0.039117
WoodDeckSF,-0.012579,0.088521,0.171698,0.238923,-0.003334,0.224880,0.205726,0.159718,0.204306,0.067898,...,0.226342,1.000000,0.058661,-0.125989,-0.032771,-0.074181,0.073378,-0.009551,0.021011,0.022270
OpenPorchSF,-0.006100,0.151972,0.084774,0.308819,-0.032589,0.188686,0.226298,0.125703,0.111761,0.003093,...,0.213569,0.058661,1.000000,-0.093079,-0.005842,0.074304,0.060762,-0.018584,0.071255,-0.057619
EnclosedPorch,-0.012037,0.010700,-0.018340,-0.113937,0.070356,-0.387268,-0.193919,-0.110204,-0.102303,0.036543,...,-0.151434,-0.125989,-0.093079,1.000000,-0.037305,-0.082864,0.054203,0.018361,-0.028887,-0.009916
3SsnPorch,-0.043825,0.070029,0.020423,0.030371,0.025504,0.031355,0.045286,0.018796,0.026451,-0.029993,...,0.035765,-0.032771,-0.005842,-0.037305,1.000000,-0.031436,-0.007992,0.000354,0.029474,0.018645
ScreenPorch,-0.026030,0.041383,0.043160,0.064886,0.054811,-0.050364,-0.038740,0.061466,0.062021,0.088871,...,0.050494,-0.074181,0.074304,-0.082864,-0.031436,1.000000,0.051307,0.031946,0.023217,0.010694
PoolArea,0.008283,0.206167,0.077672,0.065166,-0.001985,0.004950,0.005829,0.011723,0.140491,0.041709,...,0.020934,0.073378,0.060762,0.054203,-0.007992,0.051307,1.000000,0.029669,-0.033737,-0.059689
MiscVal,-0.007683,0.003368,0.038068,-0.031406,0.068777,-0.034383,-0.010286,-0.029815,0.003571,0.004940,...,-0.043080,-0.009551,-0.018584,0.018361,0.000354,0.031946,0.029669,1.000000,-0.006495,0.004906
MoSold,-0.013585,0.011200,0.001205,0.070815,-0.003511,0.012398,0.021490,-0.005965,-0.015727,-0.015211,...,0.040522,0.021011,0.071255,-0.028887,0.029474,0.023217,-0.033737,-0.006495,1.000000,-0.145721
YrSold,-0.021407,0.007450,-0.014261,-0.027347,0.043950,-0.013618,0.035743,-0.008201,0.014359,0.031706,...,-0.039117,0.022270,-0.057619,-0.009916,0.018645,0.010694,-0.059689,0.004906,-0.145721,1.000000

In [89]:
df_imputed = X[X_numerical].apply(lambda x: x.fillna(x.mean()), axis=0)

# Compute correlation matrix
correlation_matrix = df_imputed.corr()

# Find the most correlated variables (excluding self-correlation)
correlation_pairs = correlation_matrix.unstack()
correlation_pairs = correlation_pairs[correlation_pairs != 1]  # Remove self-correlation
most_correlated = correlation_pairs.sort_values(ascending=False).drop_duplicates()

# Display the most correlated variables
print(most_correlated.head())

1stFlrSF      TotalBsmtSF    0.819530
YearBuilt     GarageYrBlt    0.780555
GrLivArea     2ndFlrSF       0.687501
BsmtFullBath  BsmtFinSF1     0.649212
GrLivArea     FullBath       0.630012
dtype: float64

In [90]:
X.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2008,WD,Normal
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,5,2007,WD,Normal
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,9,2008,WD,Normal
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,NaN,NaN,0,12,2008,WD,Normal

In [91]:
# Filling the missing numerical values with the mean
#numerical_transformer = SimpleImputer(strategy = 'mean')
numerical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler())  #scaling for Lasso
])

In [56]:
# Filling the missing categorical values with the most frequent, and convert them to numerical using one-hot encoding
    # Pipeline encapsulates the process of data preparation and model training into a single object
categorical_transformer = Pipeline(steps = [
    ('imputer', SimpleImputer(strategy = 'most_frequent')),
    ('onehot', OneHotEncoder(handle_unknown = 'ignore'))
])

In [57]:
# specify which features in the dataset are numerical and which are categorical
preprocessor = ColumnTransformer( transformers = [
    ('num', numerical_transformer, X_numerical),
    ('cat', categorical_transformer, X_categorical)
])

In [58]:
###############

In [93]:
# Define the model
#model = Pipeline(steps = [
#    ('preprocessor', preprocessor),
#    ('model', LinearRegression())
#])


model = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('lasso', Lasso(max_iter=500000))
])

In [94]:
param_grid = {
    'lasso__alpha': [0.01, 0.1, 1, 10, 100]  #different alpha values for tuning
}

In [95]:
grid_search = GridSearchCV(model, param_grid, cv=5, scoring='neg_mean_squared_error')

In [96]:
# Split the data into training and validation (testing) sets
X_train, X_val, y_train, y_val = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [97]:
# Train the model
#model.fit(X_train, y_train)
grid_search.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(transformers=[('num',
                                                                         SimpleImputer(),
                                                                         ['MSSubClass',
                                                                          'LotFrontage',
                                                                          'LotArea',
                                                                          'OverallQual',
                                                                          'OverallCond',
                                                                          'YearBuilt',
                                                                          'YearRemodAdd',
                                                                          'MasVnrArea',
                                                                          'BsmtFinSF1',
                                                                          'BsmtFinSF2',
                                                                          'BsmtUnfSF',
                                                                          'TotalBsmtSF',
                                                                          '1stFlrSF',
                                                                          '2ndFlrSF',
                                                                          'LowQualFinSF',
                                                                          'GrLivArea',
                                                                          'BsmtFullBath',
                                                                          'BsmtHalfBath...
                                                                          'HouseStyle',
                                                                          'RoofStyle',
                                                                          'RoofMatl',
                                                                          'Exterior1st',
                                                                          'Exterior2nd',
                                                                          'MasVnrType',
                                                                          'ExterQual',
                                                                          'ExterCond',
                                                                          'Foundation',
                                                                          'BsmtQual',
                                                                          'BsmtCond',
                                                                          'BsmtExposure',
                                                                          'BsmtFinType1',
                                                                          'BsmtFinType2',
                                                                          'Heating',
                                                                          'HeatingQC',
                                                                          'CentralAir',
                                                                          'Electrical', ...])])),
                                       ('lasso', Lasso(max_iter=500000))]),
             param_grid={'lasso__alpha': [0.01, 0.1, 1, 10, 100]},
             scoring='neg_mean_squared_error')

In [98]:
# Make predictions
y_pred = grid_search.predict(X_val)

In [99]:
# Predict test file
y_test = grid_search.predict(X_test)

In [100]:
# saving it into a new file called LinearRegressionResult
output = pd.DataFrame({'Id': test_data['Id'], 'SalePrice': y_test})
output.to_csv('LinearRegressionResult.csv', index=False)

In [101]:
# Evaluate the model
mse = mean_squared_error(y_val, y_pred)
print(f'Mean Squared Error: {mse}')

Mean Squared Error: 793478724.9057013

In [102]:
rmse = mean_squared_error(y_val, y_pred, squared = False)
print(rmse)

28168.754408132805

In [103]:
r2_score(y_val, y_pred)

0.8965521539146264

In [ ]:
cv_scores = cross_val_score(grid_search, X, y, cv=5, scoring='neg_mean_squared_error')
print(f'Cross-Validated MSE: {-np.mean(cv_scores)}')

In [ ]:
# Plotting the results
plt.figure(figsize=(10, 6))
plt.bar(output['Id'][:50], output['SalePrice'][:50])
plt.xlabel('Id')
plt.ylabel('SalePrice')
plt.title('House Prices Predictions')
plt.xticks(rotation=90)
plt.show()